name: workspace_CI

on:
    push:
        branches: [workspace_publish]
    workflow_dispatch:
jobs:
  release:
        # You also can use the self-hosted runners.
    runs-on: windows-latest
    steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - name: synapse workspace deployment
          uses: azure/synapse-workspace-deployment@release-1.0
          with:
            TargetWorkspaceName: 'vassynapseuat'
            TemplateFile: './vassynapsedev/TemplateForWorkspace.json'
            ParametersFile: './vassynapsedev/TemplateParametersForWorkspace.json'
           # OverrideArmParameters: './path of the parameters.yaml'
            environment: 'Azure Public'
            resourceGroup: 'vasgroup'
            clientId: 'ed376c09-c03a-4827-93c1-fc99df409b87'
            clientSecret: '41q8Q~qJLU36NwVd7NuO67U7cPizOWhxXWwuFdnA'
            subscriptionId: '0efd0e57-a7dd-4bf4-9471-a92a8a9d503a'
            tenantId: '3d34eb6d-1a2e-4803-a2ff-ec537e88d92c'
            DeleteArtifactsNotInTemplate: 'false'
            managedIdentity: 'False'
